#define Introduction 0
#define Welcome 1
#define Whatsnew 2
#define GettingStarted 3
#define Systemrequirements 4
#define Gettinghelp 5
#define Howtoconnect 29
#define Howtoreaddata 30
#define Howtosavedata 44
#define Howtoprintdata 45
#define Howtodisconnect 80
#define Howtoviewjumpprofile 104
#define Howtoviewprofilesgraphs 105
#define Howtoviewandprintstatistics 106
#define Screens 36
#define Dataitemstreeview 69
#define Deviceinformation 70
#define Displaysettings 71
#define Alarms 72
#define Alarmsnames1 73
#define Alarmstones 74
#define Dropzonenames 75
#define Aircraftnames 76
#define Speedgroups1 77
#define Logbooksummary 78
#define Jumpsdetails1 79
#define Jumpprofile 100
#define Jumpsprofilesgraphs 101
#define Dataexchange 37
#define Tools 38
#define Statistics 102
#define Commands 39
#define Devicemenu 40
#define Connect 46
#define Disconnect 47
#define ReadSelected 48
#define ReadAll 49
#define ReadArchive 50
#define SaveSelected 51
#define SaveAll 52
#define Save 53
#define Print 54
#define PrintPreview 55
#define PageSetup 56
#define Exit 57
#define Viewmenu 41
#define CollapsAll 58
#define ExpandAll 59
#define SelectAll 60
#define UnselectAll 61
#define Showdataexchange 62
#define Optionsmenu 42
#define Settings 63
#define Tools1 64
#define Statistics1 103
#define Helpmenu 43
#define Content 65
#define Index 66
#define Protocol 67
#define About 68
#define Filemenu 108
#define Save1 109
#define Print1 110
#define Printpreview1 111
#define Pagesetup1 112
#define Close 113
#define Settingsdialogbox 31
#define Connectionpage 32
#define Autoconnect 81
#define Readdataonconnection 82
#define Availableports 83
#define Baudrate 84
#define Pause 85
#define Timeout 86
#define Sendpacketretries 87
#define Communicationpage 33
#define Logdataexchangetofile 88
#define Showsdataexchangeonscreen 89
#define CSVfiledelimeters 90
#define Toolsshowsdata 91
#define Locationspage 34
#define Defaultfolder 92
#define Logfile 93
#define Errorslogfile 94
#define Appearancepage 35
#define Altitudemeasures 95
#define Speedmeasures 96
#define Resolveindextoname 97
#define Printandshowjumpsdetailscolumns 98
#define Altimastercommunicationprotocol 6
#define Thecommunicationorder 9
#define Gettype0recordcommand 10
#define Readmemorycommand 11
#define Endcommunicationcommand 12
#define Keepalivecommand 99
#define Othercommands 28
#define Encryptionalgorithm 8
#define Howtogenerateencryptionkey 25
#define Howtoencryptpacket 26
#define Howtodecryptpacket 27
#define Datastructures 7
#define Addressesinmemory 13
#define Type0record 14
#define Devicesettings 15
#define Dropzonesnames 18
#define Aircraftsnames 19
#define Speedgroups 21
#define Alarmssettings 17
#define Alarmsnames 20
#define Alarmtonedirectory 22
#define Alarmtonedata 23
#define Jumpssummary 16
#define Jumpsdetails 24
#define Jumpprofile1 107
